version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: api_requests_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - D:\Learning\PROJECTS\Interview tasks\pgsql:/usr/lib/
    build: .
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: yappank17@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
